//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUNApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public long Adm_ID { get; set; }
        public string Adm_Nombre { get; set; }
        public string Adm_Apellido { get; set; }
        public string Adm_Email { get; set; }
        public string Adm_Password { get; set; }
    }
}
